export let Juegos = [
    { 
        id: 1,
        miniatura: "../imagenes/imagenes de data/GameBoys/1.jpg",
        Category:"Games for boys",
        precio:"75.000",
        Todos:"Todos",
    },
    { 
        id: 2,
        miniatura: "../imagenes/imagenes de data/GameBoys/2.jpg",
        Category:"Games for boys",
        precio:"25.000",
        Todos:"Todos",
    },
    { 
        id: 3,
        miniatura: "../imagenes/imagenes de data/GameBoys/3.jpg",
        Category:"Games for boys",
        precio:"20.000",
        Todos:"Todos",
    },
    { 
        id: 4,
        miniatura: "../imagenes/imagenes de data/GameBoys/4.jpg",
        Category:"Games for boys",
        precio:"12.000",
        Todos:"Todos",
    },
    { 
        id: 5,
        miniatura: "../imagenes/imagenes de data/GameBoys/5.jpg",
        Category:"Games for boys",
        precio:"10.000",
        Todos:"Todos",
    },
    { 
        id: 6,
        miniatura: "../imagenes/imagenes de data/GameBoys/6.jpg",
        Category:"Games for boys",
        precio:"20.000",
        Todos:"Todos",
    },
    { 
        id: 7,
        miniatura: "../imagenes/imagenes de data/GameBoys/7.jpg",
        Category:"Games for boys",
        precio:"32.000",
        Todos:"Todos",
    },
    { 
        id:8,
        miniatura: "../imagenes/imagenes de data/GameBoys/8.jpg",
        Category:"Games for boys",
        precio:"10.000",
        Todos:"Todos",
    },
    { 
        id:9,
        miniatura: "../imagenes/imagenes de data/GameBoys/9.jpg",
        Category:"Games for boys",
        precio:"2.000",
        Todos:"Todos",
    },
    { 
        id:10,
        miniatura: "../imagenes/imagenes de data/GameBoys/10.jpg",
        Category:"Games for boys",
        precio:"22.000",
        Todos:"Todos",
    },
    { 
        id:11,
        miniatura: "../imagenes/imagenes de data/GameBoys/11.jpg",
        Category:"Games for boys",
        precio:"80.000",
        Todos:"Todos",
    },
    { 
        id:12,
        miniatura: "../imagenes/imagenes de data/GameBoys/12.jpg",
        Category:"Games for boys",
        precio:"30.000",
        Todos:"Todos",
    },
    { 
        id:13,
        miniatura: "../imagenes/imagenes de data/GameBoys/13.jpg",
        Category:"Games for boys",
        precio:"12.000",
        Todos:"Todos",
    },
    { 
        id:14,
        miniatura: "../imagenes/imagenes de data/GameBoys/14.jpg",
        Category:"Games for boys",
        precio:"8.000",
        Todos:"Todos",
    },
    { 
        id:15,
        miniatura: "../imagenes/imagenes de data/GameBoys/15.jpg",
        Category:"Games for boys",
        precio:"18.000",
        Todos:"Todos",
    },
    { 
        id:16,
        miniatura: "../imagenes/imagenes de data/GameGirls/1.jpg",
        Category:"Games for girls",
        precio:"90.000",
        Todos:"Todos",
    },
    { 
        id:17,
        miniatura: "../imagenes/imagenes de data/GameGirls/2.jpg",
        Category:"Games for girls",
        precio:"17.000",
        Todos:"Todos",
    },
    { 
        id:18,
        miniatura: "../imagenes/imagenes de data/GameGirls/3.jpg",
        Category:"Games for girls",
        precio:"18.000",
        Todos:"Todos",
    },
    { 
        id:19,
        miniatura: "../imagenes/imagenes de data/GameGirls/4.jpg",
        Category:"Games for girls",
        precio:"20.000",
        Todos:"Todos",
    },
    { 
        id:20,
        miniatura: "../imagenes/imagenes de data/GameGirls/5.jpg",
        Category:"Games for girls",
        precio:"90.000",
        Todos:"Todos",
    },
    { 
        id:21,
        miniatura: "../imagenes/imagenes de data/GameGirls/6.jpg",
        Category:"Games for girls",
        precio:"70.000",
        Todos:"Todos",
    },
    { 
        id:22,
        miniatura: "../imagenes/imagenes de data/GameGirls/7.jpg",
        Category:"Games for girls",
        precio:"5.000",
        Todos:"Todos",
    },
    { 
        id:23,
        miniatura: "../imagenes/imagenes de data/GameGirls/8.jpg",
        Category:"Games for girls",
        precio:"1.000",
        Todos:"Todos",
    },
    { 
        id:24,
        miniatura: "../imagenes/imagenes de data/GameGirls/9.jpg",
        Category:"Games for girls",
        precio:"8.000",
        Todos:"Todos",
    },
    { 
        id:25,
        miniatura: "../imagenes/imagenes de data/GameGirls/10.jpg",
        Category:"Games for girls",
        precio:"10.000",
        Todos:"Todos",
    },
    { 
        id:26,
        miniatura: "../imagenes/imagenes de data/GameGirls/11.jpg",
        Category:"Games for girls",
        precio:"40.000",
        Todos:"Todos",
    },
    { 
        id: 27,
        miniatura: "../imagenes/imagenes de data/GameGirls/12.jpg",
        Category:"Games for girls",
        precio:"45.000",
        Todos:"Todos",
    },
    { 
        id:28,
        miniatura: "../imagenes/imagenes de data/GameGirls/13.jpg",
        Category:"Games for girls",
        precio:"25.000",
        Todos:"Todos",
    },
    { 
        id:29,
        miniatura: "../imagenes/imagenes de data/GameGirls/14.jpg",
        Category:"Games for girls",
        precio:"27.000",
        Todos:"Todos",
    },
    { 
        id:30,
        miniatura: "../imagenes/imagenes de data/GameGirls/15.jpg",
        Category:"Games for girls",
        precio:"37.000",
        Todos:"Todos",
    },
]
    
